In [4]:
# !pip install pandas

In [6]:
import pandas as pd

In [11]:
train=pd.read_excel('Gen_AI Dataset.xlsx',sheet_name='Train-Set')

In [12]:
train

,Query,Assessment_url
0,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
1,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
2,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
3,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
4,I am hiring for Java developers who can also c...,https://www.shl.com/products/product-catalog/v...
...,...,...
60,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
61,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
62,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
63,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...
64,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...

In [20]:
train.drop_duplicates(subset='Query')

,Query,Assessment_url
0,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
5,I want to hire new graduates for a sales role ...,https://www.shl.com/solutions/products/product...
14,I am looking for a COO for my company in China...,https://www.shl.com/products/product-catalog/v...
20,KEY RESPONSIBITILES:\n\nManage the sound-scape...,https://www.shl.com/solutions/products/product...
25,"Content Writer required, expert in English and...",https://www.shl.com/products/product-catalog/v...
30,Find me 1 hour long assesment for the below jo...,https://www.shl.com/solutions/products/product...
39,"ICICI Bank Assistant Admin, Experience require...",https://www.shl.com/solutions/products/product...
45,We're looking for a Marketing Manager who can ...,https://www.shl.com/solutions/products/product...
50,Based on the JD below recommend me assessment ...,https://www.shl.com/solutions/products/product...
55,I want to hire a Senior Data Analyst with 5 ye...,https://www.shl.com/solutions/products/product...

In [22]:
ground_truth = {}
for _, row in train.iterrows():
    query = row['Query']
    if query not in ground_truth:
        ground_truth[query] = []
    ground_truth[query].append(row['Assessment_url'])

In [23]:
ground_truth

{'I am hiring for Java developers who can also collaborate effectively with my business teams. Looking for an assessment(s) that can be completed in 40 minutes.': ['https://www.shl.com/solutions/products/product-catalog/view/automata-fix-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/core-java-entry-level-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/java-8-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/core-java-advanced-level-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/'],
 'I want to hire new graduates for a sales role in my company, the budget is for about an hour for each test. Give me some options': ['https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-7-1/',
  'https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-sift-out-7-1/',
  'https://www.shl.com/solutions/products/product-catalog/view/entry-level-sales-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/sales-representative-solution/',
  'https://www.shl.com/products/product-catalog/view/business-communication-adaptive/',
  'https://www.shl.com/solutions/products/product-catalog/view/technical-sales-associate-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/svar-spoken-english-indian-accent-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/',
  'https://www.shl.com/solutions/products/product-catalog/view/english-comprehension-new/'],
 'I am looking for a COO for my company in China and I want to see if they are culturally a right fit for our company. Suggest me an assessment that they can complete in about an hour': ['https://www.shl.com/products/product-catalog/view/enterprise-leadership-report/',
  'https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/opq-leadership-report/',
  'https://www.shl.com/solutions/products/product-catalog/view/opq-team-types-and-leadership-styles-report',
  'https://www.shl.com/products/product-catalog/view/enterprise-leadership-report-2-0/',
  'https://www.shl.com/solutions/products/product-catalog/view/global-skills-assessment/'],
 'KEY RESPONSIBITILES:\n\nManage the sound-scape of the station through appropriate creative and marketing interventions to Increase or Maintain the listenership\nActs as an interface between Programming & sales team, thereby supporting the sales team by providing creative inputs in order to increase the overall ad spends by clients\nBuild brand Mirchi by ideating fresh programming initiatives on air campaigns, programming led on-ground events & new properties to ensure brand differentiation & thus increase brand recall at station level\nInvest time in local RJs to grow & develop them as local celebrities\nThrough strong networking, must focus on identifying the best of local talent and ensure to bring the creative minds from the market on board with Mirchi\nBuild radio as a category for both listeners & advertisers\nPeople Management\nIdentifying the right talent and investing time in developing them by frequent feedback on their performance\nMonitor, Coach and mentor team members on a regular basis\nDevelopment of Jocks as per guidelines\nMust have an eye to spot the local talent to fill up vacancies locally\n\n\n\n\nTECHNICAL SKILLS & QUALIFICATION REQUIRED:\n\nGraduation / Post Graduation (Any specialisation) with 8 -12 years of relevant experience\nExperience in digital content conceptualisation\nStrong branding focus\nMust be well-read in variety of areas and must keep up with the latest events in the city / cluster / country\nMust know to read, write & speak English \n\n\nPERSONAL ATTRIBUTES:\n\nExcellent communication skills\nGood interpersonal skills\nPeople management\n\n\nSuggest me some tests for the above jd. The duration should be at most 90 mins': ['https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-ability-next-generation/',
  'https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/',
  'https://www.shl.com/solutions/products/product-catalog/view/marketing-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/english-comprehension-new/',
  'https://www.shl.com/products/product-catalog/view/interpersonal-communications/'],
 'Content Writer required, expert in English and SEO.': ['https://www.shl.com/products/product-catalog/view/english-comprehension-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/drupal-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/written-english-v1/',
  'https://www.shl.com/solutions/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/search-engine-optimization-new/'],
 'Find me 1 hour long assesment for the below job at SHL\nJob Description\n\n Join a community that is shaping the future of work! SHL, People Science. People Answers. \n\nAre you a seasoned QA Engineer with a flair for innovation? Are you ready to shape the future of talent assessment and empower organizations to unlock their full potential? If so, we want you to be a part of the SHL Team! As a QA Engineer, you will be involved in creating and implementing software solutions that contribute to the development of our ground-breaking products.\n\nAn excellent benefit package is offered in a culture where career development, with ongoing manager guidance, collaboration, flexibility, diversity, and inclusivity are all intrinsic to our culture.\u202f There is a huge investment in SHL currently so there’s no better time to become a part of something transformational.\n\nWhat You Will Be Doing\n\n Getting involved in engineering quality assurance and providing inputs when required. \n Create and develop test plans for various forms of testing. \n Conducts and/or participates in formal and informal test case reviews. \n Develop and initiate functional tests and regression tests. \n Rolling out improvements for testing and quality processes. \n\nEssential\n\n What we are looking for from you: \n\n Development experience – Java or JavaScript, CSS, HTML (Automation) \n Selenium WebDriver and page object design pattern (Automation) \n SQL server knowledge \n Test case management experience. \n Manual Testing \n\nDesirable\n\n Knowledge the basic concepts of testing \n Strong solution-finding experience \n Strong verbal and written communicator. \n\nGet In Touch\n\nFind out how this one-off opportunity can help you achieve your career goals by making an application to our knowledgeable and friendly Talent Acquisition team. Choose a new path with SHL.\n\n #CareersAtSHL #SHLHiringTalent \n\n#TechnologyJobs #QualityAssuranceJobs\n\n#CareerOpportunities #JobOpportunities \n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science and technology.\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science and business transformation.\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nWhat SHL Can Offer You\n\nDiversity, equity, inclusion and accessibility are key threads in the fabric of SHL’s business and culture (find out more about DEI and accessibility at SHL )\nEmployee benefits package that takes care of you and your family.\nSupport, coaching, and on-the-job development to achieve career success\nA fun and flexible workplace where you’ll be inspired to do your best work (find out more LifeAtSHL )\nThe ability to transform workplaces around the world for others.\n\nSHL is an equal opportunity employer. We support and encourage applications from a diverse range of candidates. We can, and do make adjustments to make sure our recruitment process is as inclusive as possible.\n\nSHL is an equal opportunity employer.': ['https://www.shl.com/solutions/products/product-catalog/view/automata-selenium/',
  'https://www.shl.com/products/product-catalog/view/professional-7-1-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/javascript-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/htmlcss-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/css3-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/selenium-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/sql-server-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/manual-testing-new/'],
 'ICICI Bank Assistant Admin, Experience required 0-2 years, test should be 30-40 mins long': ['https://www.shl.com/solutions/products/product-catalog/view/administrative-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-ability/',
  'https://www.shl.com/solutions/products/product-catalog/view/financial-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/bank-administrative-assistant-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/general-entry-level-data-entry-7-0-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/basic-computer-literacy-windows-10-new/'],
 "We're looking for a Marketing Manager who can drive Recro’s brand positioning, community growth, and overall marketing strategy to fuel business growth. The ideal candidate is a strategic thinker, an execution-focused leader, and an expert in building high-performing marketing teams.\n\n\n\nAbout Recro \n\n\nRecro is a developer-focused platform that was founded to match individual expertise with the right opportunities seamlessly. We empower talented developers by providing them with relevant experience at fast-growing startups based on technical competencies and aspirations. These opportunities have a significant impact on their career success and help them become their best self.\n\n\nAbout The Role\n\nDevelop and execute Recro’s marketing strategy to enhance community engagement, brand positioning, and industry presence.\nLead the marketing team and oversee all functions, with a strong focus on community building, events, brand positioning, social media engagement, and market intelligence.\nDrive demand generation by leveraging community-driven initiatives, influencer partnerships, and strategic event participation.\nOrganize and represent Recro at industry conferences, networking events, and developer meetups to strengthen brand positioning.\nBuild and nurture relationships with industry influencers, developer communities, and partners to create brand advocates.\nOwn the marketing funnel, ensuring continuous tracking, analysis, and optimization of community engagement and event performance.\nCollaborate with sales, business development, and leadership teams to align marketing strategies with business objectives and market trends.\nManage marketing budgets, prioritizing event sponsorships, partnerships, and community-driven growth initiatives.\nDevelop compelling content strategies to drive community interaction and thought leadership.\nStay ahead of industry trends, competitor movements, and emerging social and market intelligence to maintain a competitive edge\n\n\nRequirements\n\n5+ years of experience in B2B marketing with a strong focus on community building, events, and brand positioning.\nHas a deep understanding how demand generation works from traditional and new age channels\nProven track record of executing large-scale events and community-driven initiatives.\nExperience in developing partnerships with industry influencers and thought leaders.\nStrong understanding of social media dynamics and community engagement strategies.\nAbility to leverage market intelligence and competitor insights to refine marketing strategies.\nExceptional storytelling and brand communication skills.\nHands-on experience with event management, sponsorships, and partnership collaborations.\nExperience in building a thriving developer or tech community is a plus.\nOpen for flexible work timings as per target geographies.\n\nI have no bar on duration.": ['https://www.shl.com/solutions/products/product-catalog/view/manager-8-0-jfa-4310/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-essentials-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/digital-advertising-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/',
  'https://www.shl.com/solutions/products/product-catalog/view/writex-email-writing-sales-new/'],
 'Based on the JD below recommend me assessment for the Consultant position in my organizations. The assessment should not be more than 90 mins\nb Description\n\n Job Purpose \n\nResponsibilities\n\nThe Consultant role supports the broader professional services organization by leading the delivery of impactful client solutions and advising on client programs. Consultants are expected to deliver solutions, services, and insights that are driven by industry best practices and that positively impact client business objectives and partnerships. Individuals in this role provide I/O technical guidance to internal and external stakeholders, and drive continuous improvement related to project delivery.  Primary Duties and Responsibilities  Primary job duties and responsibilities include but may not be limited to:\n\n Planning, executing, and documenting projects related to clients’ talent assessment and development needs (e.g., job analysis, validation, leadership assessment, succession planning, program implementation, adverse impact analyses, best practices). \n Leading projects; ensuring overall quality for all client deliverables and guiding other to do the same. \n Serving as an expert resource to clients and internal stakeholders about issues related to talent assessment, selection, and development. \n Linking human capital insights to business outcomes and demonstrating ROI. \n Collaborating with members of the Sales team to manage existing programs and identify new business opportunities. \n Maintaining up-to-date knowledge of the field including empirical research, industry trends, and competitors. \n Providing talent analytics and data insights to technical and non-technical stakeholders. \n Contributing to the ongoing definition and development of SHL’s offerings and methodologies. \n Presenting to and interacting with senior client stakeholders. \n Providing thought leadership; working with delivery and commercial teams to drive improvements in the scoping and execution of projects/deliverables. \n\n Key Competencies: \n\n Decision Making \n Collaboration \n Building Relationships \n Creativity and Innovation \n Planning and Organizing \n Delivering Results \n Adaptability \n\n Qualifications include: \n\n A graduate degree in Industrial/Organizational psychology or a related discipline \n 2+ years of relevant work experience in applied talent assessment, talent management, or employee selection, including program design and implementation \n Client-facing delivery experience with design and implementation of talent assessment programs (including job analysis, criterion validation, content validation, and interviews) \n Selection system development and / or evaluation \n Proficient in at least one statistical program (e.g., SPSS, R) \n Strong communication skills and presenting technical results to non-technical stakeholders \n\n#IO #IndustrialPsychology #psychtalent #talentmanagement #talentassessment #psychometrics #consultant\n\nAbout Us\n\nWe unlock the possibilities of businesses through the power of people, science, and technology.\n\nWe started this industry of people insight more than 40 years ago and continue to lead the market with powerhouse product launches, ground-breaking science, and business transformation.\n\nWhen you inspire and transform people’s lives, you will experience the greatest business outcomes possible. SHL’s products insights, experiences, and services can help achieve growth at scale.\n\nMore at shl.com.\n\nWhat SHL Can Offer You\n\n An inclusive culture. \n A fun and flexible workplace where you’ll be inspired to do your best work. \n Employee benefits package that takes care of you and your family. \n Support, coaching, and on-the-job development to achieve career success. \n The ability to transform workplaces around the world for others. \n\nSHL is an equal opportunity employer.': ['https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-numerical-calculation/',
  'https://www.shl.com/solutions/products/product-catalog/view/administrative-professional-short-form/',
  'https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-ability-next-generation/',
  'https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-1-solution/'],
 'I want to hire a Senior Data Analyst with 5 years of experience and expertise in SQL, Excel and Python. The assessment can be 1-2 hour long': ['https://www.shl.com/solutions/products/product-catalog/view/sql-server-analysis-services-%28ssas%29-%28new%29/',
  'https://www.shl.com/solutions/products/product-catalog/view/sql-server-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/automata-sql-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/python-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/tableau-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/microsoft-excel-365-essentials-new/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-0-solution-3958/',
  'https://www.shl.com/solutions/products/product-catalog/view/professional-7-1-solution/',
  'https://www.shl.com/solutions/products/product-catalog/view/data-warehousing-concepts/']}

In [24]:
from google import genai
client = genai.Client()
for model in client.models.list():
    print(model.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-exp-image-generation
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-2.5-flash-lite-preview-09-2025
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-robotics-er-1.5-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025

In [27]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings,ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model="gemini-3-flash-preview",
    temperature=0.3,    # low temperature for factual, consistent recommendations
)

In [28]:
llm.invoke("hello")

KeyboardInterrupt: